version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      exclude:
        - "@knocklabs/*"
        - "@telegraph/*"
    commit-message:
      prefix: "chore"
      include: "scope"
    versioning-strategy: increase
    open-pull-requests-limit: 5
    groups:
      telegraph-packages:
        patterns:
          - "@telegraph/*"
